{% set name = "xeus-octave" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapgenic/xeus-octave/archive/{{ version }}.tar.gz
  sha256: baadb52f4783fff106c7351692175ef97eb9c4969c1d82ae8f78f00efe1997b2
  patches:
    - comment-shutdown-call.patch 

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - ninja
    - pkg-config  # [osx]
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - nlohmann_json >=3.9.1,<4.0
    - octave >=7.0,<8.0
    - xeus >=1.0,<2.0
    - xproperty
    - xorg-libxfixes  # [linux]
    - glfw
    - libpng
  run:
    - glfw
    # Octave is missing a run_exports section
    - {{ pin_compatible('octave', max_pin='x.x') }}

test:
  commands:
    - test -f ${PREFIX}/bin/xeus-octave  # [unix]

about:
  home: https://github.com/rapgenic/xeus-octave
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: 'xeus kernel for octave'

  description: |
    xeus kernel for the mathematics-oriented syntax with built-in
    2D/3D plotting and visualization tools octave.

extra:
  recipe-maintainers:
    - rapgenic
    - marimeireles
    - SylvainCorlay
