{% set name = "xeus-octave" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-octave/archive/v{{ version }}.tar.gz
  sha256: 41a9fb6157c336b8782b42f09cf9b5e102b351a4175a393b7ef4ce05f90f9d1b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - pkg-config  # [osx]
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - octave >=7.0,<8.0
    - xorg-libxfixes  # [linux]
    - glfw
    - mesalib
    - libpng
    - xeus >=2.4,<3.0
    - nlohmann_json >=3.9.1,<4.0
    - cppzmq
    - xtl >=0.7,<1.0
    - xproperty

  run:
    - glfw
    # Octave is missing a run_exports section
    - {{ pin_compatible('octave', max_pin='x.x') }}
    # Mesalib is missing a run_exports section
    - {{ pin_compatible('mesalib', max_pin='x.x') }}

test:
  commands:
    - test -f ${PREFIX}/bin/xoctave  # [unix]
    - xoctave --version

about:
  home: https://github.com/rapgenic/xeus-octave
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: 'Xeus kernel for Octave'

  description: |
    Xeus kernel for the mathematics-oriented syntax with built-in
    2D/3D plotting and visualization tools Octave.

extra:
  recipe-maintainers:
    - rapgenic
    - marimeireles
    - SylvainCorlay
    - AntoinePrv
